version: '3'
services:
  mongo:
    container_name: mongo1
    image: mongo:latest
    expose:
      - "27017"
  kafka:
    container_name: steanleo/kafka
    image: kafkai
    expose:
      - "2181"
      - "9092"
  spark:
    container_name: spark1
    image: steanleo/spark
  flask:
    container_name: flask1
    image: steanleo/flask
    expose:
      - "5000"
