version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    expose:
      - "27017"
  kafka:
    container_name: kafka
    image: steanleo/kafka
    expose:
      - "2181"
      - "9092"
  spark:
    container_name: spark
    image: steanleo/spark
  flask:
    container_name: flask
    image: steanleo/flask
    expose:
      - "5000"
