FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Madrid
ADD web/. /home/web
WORKDIR /home/web

RUN chmod 755 script.sh
RUN apt-get update && apt-get install -yqq \
  default-jdk \
  default-jre \
  nano \
  python3.8 \
  python3-pip

RUN pip install -r requirements.txt

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
#ENV PROJECT_HOME=/home/practica_big_data_2019

CMD ["/home/web/script.sh"]
EXPOSE 5000
